### ISSUE TITLE
Plans for future development

### ISSUE THREAD

**Issue by thrashdin** [gmasching/sucle#12]
Are you planning to add other minecraftish features, like char models, ui and all other stuff?

**Comment by pupcraft** [comment]
Hello Aun, long time no see!

Sucle will allow [anyone](https://github.com/pupcraft/lem-opengl) to create and mod the world of their dreams.

**Comment by Sokolov57** [comment]
Yeah, well, but will you implement this yourself here?)
I see some other minecraft clones popping up.
https://www.minetest.net/

**Comment by pupcraft** [comment]
If you don't want to use Common Lisp, you don't have to, you have free will after all

**Comment by Sokolov57** [comment]
Nono, didn't mean that. I'm absolutely sticking to CL now and then, just wondering if you plan to do this specific thing.

And the link is there just because those guys are open sourced too, so I thought you might be interested.

**Comment by pupcraft** [comment]
:) Well thank you for sharing! I'll check out minetest, pretty cool that its open source. 
Right now sucle is in the middle of a huge rewrite, so new features won't be added soon. In fact, I'm trying to remove old features that are no longer necessary.
