### ISSUE TITLE
Does not build today - missing package?

### ISSUE THREAD

**Issue by quicklisp** [gmasching/sucle#13]
I get this: ```Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10005E05B3}>: Error finding package for symbol "OBJECT":
 The name "STRUCT-TO-CLOS" does not designate any package.```

http://report.quicklisp.org/2019-04-28/failure-report/sucle.html#text-subsystem

**Comment by pupcraft** [comment]
Dear quicklisp, 
The latest commits should fix it, I updated asdf to use :vecto and :uncommon-lisp
