### ISSUE TITLE
Dirt blocks

### ISSUE THREAD

**Issue by thrashdin** [gmasching/sucle#18]
Is it intended, that dirt block have height 1/2 now?

**Comment by pupcraft** [comment]
Dearest Aun,
Congratulations! You have found the first easter egg. What does a dirt block with 1/2 height remind you of?

**Comment by thrashdin** [comment]
Well, I played many mods, so I can think of several things)
First one was "mud" blocks from I don't remember which mod.
Also I m not aware of many minecraft memes in case this is one of them)

**Comment by pupcraft** [comment]
Don't worry about it, its a deep minecraft meme. 
Also, what types of mods do you like and which are your favorite?

**Comment by thrashdin** [comment]
Well, those ones))
https://www.technicpack.net/modpack/mcnewhorizons.677387
I dream about a day when an intersection of minecraft and lisp community will be able to duplicate that thing, but in your project and without buggy spaghetti scripts))

**Comment by pupcraft** [comment]
GT New Horizons looks pretty cool! There are some mods there that I recognize, like Thaumcraft. Have you heard of Project Ozone?

I built Sucle with four purposes in mind, and try to keep things as simple as possible:
- Parkour
- Voxel editing, world generation
- Infinite worlds, in x, y, and z
- Being pretty

But in order for Sucle to support mods like GT New Horizons, Sucle would need:
- Mobs
- Items
- Menus/ui 
- Dimensions 

I'll see what I can do but can't guarantee it.

**Comment by thrashdin** [comment]
Sure, and this would require __a lot__ of work, so it's not something I expect you to do -- this is just something I dream of when I look at your package) And I think this is already a good thing.
