### ISSUE TITLE
GLSL issue

### ISSUE THREAD

**Issue by gravitational-dark-light** [gmasching/sucle#36]
When I try to start sucle, I always get this error for some reason:

![sucle-error](https://user-images.githubusercontent.com/8922976/72668757-69f07a00-3a00-11ea-8cfb-2ba1f6a56e82.png)
![sucle-error-2](https://user-images.githubusercontent.com/8922976/72668756-69f07a00-3a00-11ea-993a-dbb39bbaacdc.png)
![sucle-error-3](https://user-images.githubusercontent.com/8922976/72668755-69f07a00-3a00-11ea-9f9c-b49c72935a81.png)

Any idea what the issue could be?

**Comment by gmasching** [comment]
Hello! Thanks for reporting this error. 

The error message indicates that your OpenGL version is 2.1 and GLSL version is 120, so when trying to compile shaders, the wrong text is emitted. 

This is not good, all GLSL versions are supported via least-common denominator features [this has been tested before, but is broken now apparently]. It has to do with improper string replacement of "out" to "varying".

This fix should take a couple of minutes, let me see...

**Comment by gmasching** [comment]
So it turns out that two function parameters were swapped, like a typo.
So `(f b a)` -> `(f a b)`
This should do the trick: https://github.com/gmasching/sucle/commit/33610669de8e427579e6e6f3111240220aa90913

Thanks!

**Comment by gravitational-dark-light** [comment]
> So it turns out that two function parameters were swapped, like a typo.
> So `(f b a)` -> `(f a b)`
> This should do the trick: [3361066](https://github.com/gmasching/sucle/commit/33610669de8e427579e6e6f3111240220aa90913)
> 
> Thanks!

Well, it's working now, thank you

**Comment by gmasching** [comment]
Also be warned that there is currently no world-generation or test world. 

You have to place all the blocks yourself or figure out how the other code works.

I really need to add a menu, or a tutorial or a help section.

**Comment by gravitational-dark-light** [comment]
Yeah, I read about that in other issues before, but that's ok, I wanted to play with things anyway

**Comment by gmasching** [comment]
Kudos for trying things out, but right now its so bare bones at the moment and undocumented that you will definitely have a hard time. If you need any help, just ask.

**Comment by gravitational-dark-light** [comment]
Will do, thanks...
